os: linux
language: python
sudo: required
services:
  - docker
env:
  global:
    - CONAN_UPLOAD: 1
    - CONAN_REFERENCE: "Sparrow/0.10"
    - CONAN_USERNAME: "lucteo"
    - CONAN_CHANNEL: "ci"
    - CONAN_TOTAL_PAGES: 1
    - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib

  matrix:
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
matrix:
   include:
       - os: osx
         osx_image: xcode8.0 # apple-clang 8.0
         language: generic
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic

install:
  - ./.travis/install.sh
script:
  - ./.travis/tryCreateTag.sh
  - ./.travis/run.sh
