language: cpp
sudo: required
dist: trusty
compiler: clang
matrix:
   include:
       - os: linux
         addons:
            apt:
                sources:
                  - llvm-toolchain-trusty-5.0
                packages:
                  - llvm-5.0-dev
                  - libboost-all-dev
                  - libedit-dev
       - os: osx
         osx_image: xcode9.2 # apple-clang 9.2, OS X 10.12

install:
  - ./.travis/install.sh
script:
  - ./.travis/tryCreateTag.sh
  - ./.travis/run.sh
after_success:
  - ./.travis/checkPerformance.sh
